// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-producers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_producers_default = defineTool({
  name: "list_producers",
  title: "Lister les producteurs",
  description: "Liste les producteurs accessibles \xE0 l'utilisateur (filtr\xE9 par RLS/registres). Retourne au plus 200 lignes.",
  inputSchema: {
    search: z.string().trim().optional().describe("Filtre optionnel sur le nom du producteur."),
    limit: z.number().int().min(1).max(200).optional().describe("Nombre max de lignes (d\xE9faut 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    const sb = sbForUser(ctx);
    let q = sb.from("producers").select("id,full_name,section,plantation_code,delivery_potential,remaining_potential,sexe,is_active,registre_id").order("full_name", { ascending: true }).limit(limit ?? 50);
    if (search) q = q.ilike("full_name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} producteur(s)` }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-shipments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_shipments_default = defineTool2({
  name: "list_shipments",
  title: "Lister les chargements",
  description: "Liste les chargements r\xE9cents accessibles \xE0 l'utilisateur (filtr\xE9 par RLS). Optionnellement filtr\xE9 par campagne.",
  inputSchema: {
    campaign_label: z2.string().trim().optional().describe("Ex: '2025-2026'."),
    limit: z2.number().int().min(1).max(200).optional().describe("Nombre max de lignes (d\xE9faut 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ campaign_label, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    const sb = sbForUser2(ctx);
    let q = sb.from("shipments").select("id,lot_number,campaign_label,total_weight,total_bags,departure_date,is_cancelled,registre_id").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (campaign_label) q = q.eq("campaign_label", campaign_label);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} chargement(s)` }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/dashboard-stats.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var dashboard_stats_default = defineTool3({
  name: "get_dashboard_stats",
  title: "Statistiques du tableau de bord",
  description: "Retourne les KPI (potentiel total, poids livr\xE9, potentiel restant, nombre de chargements et producteurs) pour un registre donn\xE9.",
  inputSchema: {
    registre_id: z3.string().uuid().describe("UUID du registre."),
    campaign_label: z3.string().trim().optional().describe("Optionnel: campagne, ex '2025-2026'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ registre_id, campaign_label }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    const sb = sbForUser3(ctx);
    const { data, error } = await sb.rpc("get_dashboard_stats_by_registre", {
      p_registre_id: registre_id,
      p_campaign_label: campaign_label ?? null
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const row = Array.isArray(data) ? data[0] : data;
    return {
      content: [{ type: "text", text: JSON.stringify(row) }],
      structuredContent: { stats: row }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qkzyllbdceteeoixoxke";
var mcp_default = defineMcp({
  name: "coops-app-mcp",
  title: "COOPS APP MCP",
  version: "0.1.0",
  instructions: "Outils m\xE9tier de COOPS APP (gestion coop\xE9ratives cacao/caf\xE9). Utilisez list_producers et list_shipments pour explorer les donn\xE9es du registre de l'utilisateur, et get_dashboard_stats pour les KPI d'un registre. Toutes les donn\xE9es sont filtr\xE9es par RLS selon l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_producers_default, list_shipments_default, dashboard_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
